version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: netology
      POSTGRES_DB: app


    ports:
      - '5432:5432'